# Generated by Django 5.1 on 2024-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='AdminTick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='AdminTick',
            field=models.BooleanField(default=False),
        ),
    ]
