# Generated by Django 5.1 on 2024-08-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0002_guest_admintick_student_admintick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfStudent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='RoomChoisen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='RoomChoisen',
        ),
        migrations.RemoveField(
            model_name='emptyroom',
            name='Rooms',
        ),
        migrations.RemoveField(
            model_name='fullroom',
            name='Rooms',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='RoomIs',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='mathroom',
            name='Rooms',
        ),
        migrations.RemoveField(
            model_name='medicalroom',
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='NumOfPeopleInRoom',
            new_name='num_of_people_in_room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='PricePerDay',
            new_name='price_per_day',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='RoomNumber',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='AdminTick',
            new_name='admin_tick',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Billing',
            new_name='billing',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='EndDay',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StartDay',
            new_name='start_day',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Feild',
        ),
        migrations.RemoveField(
            model_name='student',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='RoomIs',
        ),
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.CharField(choices=[('Math', 'Math'), ('Medical', 'Medical')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.room'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservestudent',
            name='room_chocen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_chocen', to='HostalDRF.room'),
        ),
        migrations.AddField(
            model_name='studentgroup3',
            name='stu1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu1', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup3',
            name='stu2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu2', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup3',
            name='stu3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu3', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu14', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu24', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu34', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu44', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu16', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu26', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu36', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu46', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu56', to='HostalDRF.student'),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu66', to='HostalDRF.student'),
        ),
        migrations.DeleteModel(
            name='ChosenRoom',
        ),
        migrations.DeleteModel(
            name='EmptyRoom',
        ),
        migrations.DeleteModel(
            name='FullRoom',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='MathRoom',
        ),
        migrations.DeleteModel(
            name='MedicalRoom',
        ),
    ]
