# Generated by Django 5.1 on 2024-08-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0003_reservestudent_studentgroup3_studentgroup4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservestudent',
            name='room_chocen',
        ),
        migrations.AddField(
            model_name='reservestudent',
            name='group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup3'),
        ),
        migrations.AddField(
            model_name='reservestudent',
            name='group4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup4'),
        ),
        migrations.AddField(
            model_name='reservestudent',
            name='group6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup6'),
        ),
        migrations.AddField(
            model_name='room',
            name='group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup3'),
        ),
        migrations.AddField(
            model_name='room',
            name='group4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup4'),
        ),
        migrations.AddField(
            model_name='room',
            name='group6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.studentgroup6'),
        ),
    ]
