# Generated by Django 5.1 on 2024-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0005_login_student_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
