# Generated by Django 5.1 on 2024-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0006_alter_student_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.BooleanField(default=False),
        ),
    ]
