# Generated by Django 5.1 on 2024-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0007_student_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup3',
            name='stu1_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup3',
            name='stu2_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup3',
            name='stu3_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu1_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu2_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu3_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup4',
            name='stu4_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu1_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu2_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu3_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu4_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu5_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup6',
            name='stu6_tick',
            field=models.BooleanField(default=False),
        ),
    ]
