# Generated by Django 5.1 on 2024-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0008_studentgroup3_stu1_tick_studentgroup3_stu2_tick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='billing',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
