# Generated by Django 5.1 on 2024-08-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0009_alter_student_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_day',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.room'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_day',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_user',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
