# Generated by Django 5.1 on 2024-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0012_alter_student_billing_alter_student_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
