# Generated by Django 5.1 on 2024-08-15 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0013_alter_student_end_day_alter_student_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservestudent',
            name='room_reserve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HostalDRF.room'),
        ),
    ]
