# Generated by Django 5.1 on 2024-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostalDRF', '0014_reservestudent_room_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_user', models.CharField(max_length=200, null=True, unique=True)),
                ('field', models.CharField(choices=[('Math', 'Math'), ('Medical', 'Medical')], max_length=100, null=True)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
